name: JobScrapping API
on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
permissions:
    contents: read
env:
    PERSONAL_EMAIL: ${{ secrets.PERSONAL_EMAIL }}
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set Up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run Tests and Generate Report (unittest)
              run: |
                  python -m tests
            - name: Upload Test Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: test-report
                  path: TEST-report.xml
    scripts:
        runs-on: ubuntu-latest
        steps:
            - name: Execute Shell Script
              uses: actions/checkout@v3
            - run: |
                  sh scripts/shell.sh